// DispIDs.h: Defines a DISPID for each COM property and method we're providing.

// ICheckBox
// properties
#define DISPID_CHKBOX_APPEARANCE										1
#define DISPID_CHKBOX_AUTOTOGGLECHECKMARK						2
#define DISPID_CHKBOX_BACKCOLOR											3
#define DISPID_CHKBOX_BORDERSTYLE										4
#define DISPID_CHKBOX_CHECKMARKONRIGHT							5
#define DISPID_CHKBOX_CONTENTTYPE										6
#define DISPID_CHKBOX_DISABLEDEVENTS								7
#define DISPID_CHKBOX_DONTREDRAW										8
#define DISPID_CHKBOX_ENABLED												DISPID_ENABLED
#define DISPID_CHKBOX_FONT													9
#define DISPID_CHKBOX_FORECOLOR											10
#define DISPID_CHKBOX_HALIGNMENT										11
#define DISPID_CHKBOX_HIMAGELIST										12
#define DISPID_CHKBOX_HOVERTIME											13
#define DISPID_CHKBOX_HWND													14
#define DISPID_CHKBOX_ICONALIGNMENT									15
#define DISPID_CHKBOX_ICONMARGINBOTTOM							16
#define DISPID_CHKBOX_ICONMARGINLEFT								17
#define DISPID_CHKBOX_ICONMARGINRIGHT								18
#define DISPID_CHKBOX_ICONMARGINTOP									19
#define DISPID_CHKBOX_IMAGE													20
#define DISPID_CHKBOX_MOUSEICON											21
#define DISPID_CHKBOX_MOUSEPOINTER									22
#define DISPID_CHKBOX_MULTILINE											23
#define DISPID_CHKBOX_PROCESSCONTEXTMENUKEYS				24
#define DISPID_CHKBOX_PUSHED												25
#define DISPID_CHKBOX_PUSHLIKE											26
#define DISPID_CHKBOX_REGISTERFOROLEDRAGDROP				27
#define DISPID_CHKBOX_RIGHTTOLEFT										28
#define DISPID_CHKBOX_SELECTIONSTATE								29
#define DISPID_CHKBOX_STYLE													30
#define DISPID_CHKBOX_SUPPORTOLEDRAGIMAGES					31
#define DISPID_CHKBOX_TEXT													32
#define DISPID_CHKBOX_TEXTMARGINBOTTOM							33
#define DISPID_CHKBOX_TEXTMARGINLEFT								34
#define DISPID_CHKBOX_TEXTMARGINRIGHT								35
#define DISPID_CHKBOX_TEXTMARGINTOP									36
#define DISPID_CHKBOX_TRISTATE											37
#define DISPID_CHKBOX_USESYSTEMFONT									38
#define DISPID_CHKBOX_VALIGNMENT										39
#define DISPID_CHKBOX_VERSION												40
#define DISPID_CHKBOX_ICONINDEX											46
#define DISPID_CHKBOX_USEIMPROVEDIMAGELISTSUPPORT		47
// fingerprint
#define DISPID_CHKBOX_APPID													500
#define DISPID_CHKBOX_APPNAME												501
#define DISPID_CHKBOX_APPSHORTNAME									502
#define DISPID_CHKBOX_BUILD													503
#define DISPID_CHKBOX_CHARSET												504
#define DISPID_CHKBOX_ISRELEASE											505
#define DISPID_CHKBOX_PROGRAMMER										506
#define DISPID_CHKBOX_TESTER												507
// methods
#define DISPID_CHKBOX_ABOUT													DISPID_ABOUTBOX
#define DISPID_CHKBOX_CLICK													41
#define DISPID_CHKBOX_GETCONTROLSTATE								42
#define DISPID_CHKBOX_LOADSETTINGSFROMFILE					43
#define DISPID_CHKBOX_REFRESH												DISPID_REFRESH
#define DISPID_CHKBOX_SAVESETTINGSTOFILE						44
#define DISPID_CHKBOX_GETIDEALSIZE									45
#define DISPID_CHKBOX_FINISHOLEDRAGDROP							48


// _ICheckBoxEvents
// methods
#define DISPID_CHKBOXE_CLICK												1
#define DISPID_CHKBOXE_CONTEXTMENU									2
#define DISPID_CHKBOXE_CUSTOMDRAW										3
#define DISPID_CHKBOXE_DBLCLICK											4
#define DISPID_CHKBOXE_DESTROYEDCONTROLWINDOW				5
#define DISPID_CHKBOXE_KEYDOWN											6
#define DISPID_CHKBOXE_KEYPRESS											7
#define DISPID_CHKBOXE_KEYUP												8
#define DISPID_CHKBOXE_MCLICK												9
#define DISPID_CHKBOXE_MDBLCLICK										10
#define DISPID_CHKBOXE_MOUSEDOWN										11
#define DISPID_CHKBOXE_MOUSEENTER										12
#define DISPID_CHKBOXE_MOUSEHOVER										13
#define DISPID_CHKBOXE_MOUSELEAVE										14
#define DISPID_CHKBOXE_MOUSEMOVE										15
#define DISPID_CHKBOXE_MOUSEUP											16
#define DISPID_CHKBOXE_OLEDRAGDROP									17
#define DISPID_CHKBOXE_OLEDRAGENTER									18
#define DISPID_CHKBOXE_OLEDRAGLEAVE									19
#define DISPID_CHKBOXE_OLEDRAGMOUSEMOVE							20
#define DISPID_CHKBOXE_OWNERDRAW										21
#define DISPID_CHKBOXE_RCLICK												22
#define DISPID_CHKBOXE_RDBLCLICK										23
#define DISPID_CHKBOXE_RECREATEDCONTROLWINDOW				24
#define DISPID_CHKBOXE_RESIZEDCONTROLWINDOW					25
#define DISPID_CHKBOXE_SELECTIONSTATECHANGED				DISPID_VALUE
#define DISPID_CHKBOXE_XCLICK												26
#define DISPID_CHKBOXE_XDBLCLICK										27


// ICommandButton
// properties
#define DISPID_CMDBTN_APPEARANCE										1
#define DISPID_CMDBTN_BACKCOLOR											2
#define DISPID_CMDBTN_BORDERSTYLE										3
#define DISPID_CMDBTN_CONTENTTYPE										4
#define DISPID_CMDBTN_DISABLEDEVENTS								5
#define DISPID_CMDBTN_DONTREDRAW										6
#define DISPID_CMDBTN_ENABLED												DISPID_ENABLED
#define DISPID_CMDBTN_FONT													7
#define DISPID_CMDBTN_FORECOLOR											8
#define DISPID_CMDBTN_HALIGNMENT										9
#define DISPID_CMDBTN_HIMAGELIST										10
#define DISPID_CMDBTN_HOVERTIME											11
#define DISPID_CMDBTN_HWND													12
#define DISPID_CMDBTN_ICONALIGNMENT									13
#define DISPID_CMDBTN_ICONMARGINBOTTOM							14
#define DISPID_CMDBTN_ICONMARGINLEFT								15
#define DISPID_CMDBTN_ICONMARGINRIGHT								16
#define DISPID_CMDBTN_ICONMARGINTOP									17
#define DISPID_CMDBTN_IMAGE													18
#define DISPID_CMDBTN_MOUSEICON											19
#define DISPID_CMDBTN_MOUSEPOINTER									20
#define DISPID_CMDBTN_MULTILINE											21
#define DISPID_CMDBTN_PROCESSCONTEXTMENUKEYS				22
#define DISPID_CMDBTN_PUSHED												23
#define DISPID_CMDBTN_REGISTERFOROLEDRAGDROP				24
#define DISPID_CMDBTN_RIGHTTOLEFT										25
#define DISPID_CMDBTN_STYLE													26
#define DISPID_CMDBTN_SUPPORTOLEDRAGIMAGES					27
#define DISPID_CMDBTN_TEXT													28
#define DISPID_CMDBTN_TEXTMARGINBOTTOM							29
#define DISPID_CMDBTN_TEXTMARGINLEFT								30
#define DISPID_CMDBTN_TEXTMARGINRIGHT								31
#define DISPID_CMDBTN_TEXTMARGINTOP									32
#define DISPID_CMDBTN_USESYSTEMFONT									33
#define DISPID_CMDBTN_VALIGNMENT										34
#define DISPID_CMDBTN_VERSION												35
#define DISPID_CMDBTN_BUTTONTYPE										41
#define DISPID_CMDBTN_COMMANDLINKNOTE								42
#define DISPID_CMDBTN_DROPDOWNARROWHEIGHT						43
#define DISPID_CMDBTN_DROPDOWNARROWWIDTH						44
#define DISPID_CMDBTN_DROPDOWNGLYPH									45
#define DISPID_CMDBTN_DROPDOWNONRIGHT								46
#define DISPID_CMDBTN_DROPDOWNPUSHED								47
#define DISPID_CMDBTN_DROPDOWNSTYLE									48
#define DISPID_CMDBTN_HDROPDOWNIMAGELIST						49
#define DISPID_CMDBTN_KEEPDROPDOWNARROWASPECTRATIO	50
#define DISPID_CMDBTN_SHOWRIGHTSELEVATIONICON				51
#define DISPID_CMDBTN_SHOWSPLITLINE									52
#define DISPID_CMDBTN_ICONINDEX											53
#define DISPID_CMDBTN_USEIMPROVEDIMAGELISTSUPPORT		54
// fingerprint
#define DISPID_CMDBTN_APPID													500
#define DISPID_CMDBTN_APPNAME												501
#define DISPID_CMDBTN_APPSHORTNAME									502
#define DISPID_CMDBTN_BUILD													503
#define DISPID_CMDBTN_CHARSET												504
#define DISPID_CMDBTN_ISRELEASE											505
#define DISPID_CMDBTN_PROGRAMMER										506
#define DISPID_CMDBTN_TESTER												507
// methods
#define DISPID_CMDBTN_ABOUT													DISPID_ABOUTBOX
#define DISPID_CMDBTN_CLICK													36
#define DISPID_CMDBTN_GETCONTROLSTATE								37
#define DISPID_CMDBTN_GETIDEALSIZE									38
#define DISPID_CMDBTN_LOADSETTINGSFROMFILE					39
#define DISPID_CMDBTN_REFRESH												DISPID_REFRESH
#define DISPID_CMDBTN_SAVESETTINGSTOFILE						40
#define DISPID_CMDBTN_FINISHOLEDRAGDROP							55


// _ICommandButtonEvents
// methods
#define DISPID_CMDBTNE_CLICK												DISPID_VALUE
#define DISPID_CMDBTNE_CONTEXTMENU									1
#define DISPID_CMDBTNE_CUSTOMDRAW										2
#define DISPID_CMDBTNE_DBLCLICK											3
#define DISPID_CMDBTNE_DESTROYEDCONTROLWINDOW				4
#define DISPID_CMDBTNE_KEYDOWN											5
#define DISPID_CMDBTNE_KEYPRESS											6
#define DISPID_CMDBTNE_KEYUP												7
#define DISPID_CMDBTNE_MCLICK												8
#define DISPID_CMDBTNE_MDBLCLICK										9
#define DISPID_CMDBTNE_MOUSEDOWN										10
#define DISPID_CMDBTNE_MOUSEENTER										11
#define DISPID_CMDBTNE_MOUSEHOVER										12
#define DISPID_CMDBTNE_MOUSELEAVE										13
#define DISPID_CMDBTNE_MOUSEMOVE										14
#define DISPID_CMDBTNE_MOUSEUP											15
#define DISPID_CMDBTNE_OLEDRAGDROP									16
#define DISPID_CMDBTNE_OLEDRAGENTER									17
#define DISPID_CMDBTNE_OLEDRAGLEAVE									18
#define DISPID_CMDBTNE_OLEDRAGMOUSEMOVE							19
#define DISPID_CMDBTNE_OWNERDRAW										20
#define DISPID_CMDBTNE_RCLICK												21
#define DISPID_CMDBTNE_RDBLCLICK										22
#define DISPID_CMDBTNE_RECREATEDCONTROLWINDOW				23
#define DISPID_CMDBTNE_RESIZEDCONTROLWINDOW					24
#define DISPID_CMDBTNE_CUSTOMDROPDOWNAREASIZE				25
#define DISPID_CMDBTNE_DROPDOWN											26
#define DISPID_CMDBTNE_XCLICK												27
#define DISPID_CMDBTNE_XDBLCLICK										28


// IFrame
// properties
#define DISPID_FRM_APPEARANCE												1
#define DISPID_FRM_BACKCOLOR												2
#define DISPID_FRM_BORDERSTYLE											3
#define DISPID_FRM_BORDERVISIBLE										4
#define DISPID_FRM_CONTENTTYPE											5
#define DISPID_FRM_DISABLEDEVENTS										6
#define DISPID_FRM_DONTREDRAW												7
#define DISPID_FRM_ENABLED													DISPID_ENABLED
#define DISPID_FRM_FONT															8
#define DISPID_FRM_FORECOLOR												9
#define DISPID_FRM_HALIGNMENT												10
#define DISPID_FRM_HIMAGELIST												11
#define DISPID_FRM_HOVERTIME												12
#define DISPID_FRM_HWND															13
#define DISPID_FRM_ICONALIGNMENT										14
#define DISPID_FRM_ICONMARGINBOTTOM									15
#define DISPID_FRM_ICONMARGINLEFT										16
#define DISPID_FRM_ICONMARGINRIGHT									17
#define DISPID_FRM_ICONMARGINTOP										18
#define DISPID_FRM_IMAGE														19
#define DISPID_FRM_MOUSEICON												20
#define DISPID_FRM_MOUSEPOINTER											21
#define DISPID_FRM_REGISTERFOROLEDRAGDROP						22
#define DISPID_FRM_RIGHTTOLEFT											23
#define DISPID_FRM_STYLE														24
#define DISPID_FRM_SUPPORTOLEDRAGIMAGES							25
#define DISPID_FRM_TEXT															26
#define DISPID_FRM_USESYSTEMFONT										27
#define DISPID_FRM_VERSION													28
#define DISPID_FRM_ICONINDEX												33
#define DISPID_FRM_USEIMPROVEDIMAGELISTSUPPORT			34
// fingerprint
#define DISPID_FRM_APPID														500
#define DISPID_FRM_APPNAME													501
#define DISPID_FRM_APPSHORTNAME											502
#define DISPID_FRM_BUILD														503
#define DISPID_FRM_CHARSET													504
#define DISPID_FRM_ISRELEASE												505
#define DISPID_FRM_PROGRAMMER												506
#define DISPID_FRM_TESTER														507
// methods
#define DISPID_FRM_ABOUT														DISPID_ABOUTBOX
#define DISPID_FRM_CLICK														29
#define DISPID_FRM_GETCONTROLSTATE									30
#define DISPID_FRM_LOADSETTINGSFROMFILE							31
#define DISPID_FRM_REFRESH													DISPID_REFRESH
#define DISPID_FRM_SAVESETTINGSTOFILE								32
#define DISPID_FRM_FINISHOLEDRAGDROP								35


// _IFrameEvents
// methods
#define DISPID_FRME_CLICK														DISPID_VALUE
#define DISPID_FRME_CONTEXTMENU											1
#define DISPID_FRME_DBLCLICK												2
#define DISPID_FRME_DESTROYEDCONTROLWINDOW					3
#define DISPID_FRME_MCLICK													4
#define DISPID_FRME_MDBLCLICK												5
#define DISPID_FRME_MOUSEDOWN												6
#define DISPID_FRME_MOUSEENTER											7
#define DISPID_FRME_MOUSEHOVER											8
#define DISPID_FRME_MOUSELEAVE											9
#define DISPID_FRME_MOUSEMOVE												10
#define DISPID_FRME_MOUSEUP													11
#define DISPID_FRME_OLEDRAGDROP											12
#define DISPID_FRME_OLEDRAGENTER										13
#define DISPID_FRME_OLEDRAGLEAVE										14
#define DISPID_FRME_OLEDRAGMOUSEMOVE								15
#define DISPID_FRME_OWNERDRAW												16
#define DISPID_FRME_RCLICK													17
#define DISPID_FRME_RDBLCLICK												18
#define DISPID_FRME_RECREATEDCONTROLWINDOW					19
#define DISPID_FRME_RESIZEDCONTROLWINDOW						20
#define DISPID_FRME_XCLICK													21
#define DISPID_FRME_XDBLCLICK												22


// IOptionButton
// properties
#define DISPID_OPTBTN_APPEARANCE										1
//#define DISPID_OPTBTN_AUTOTOGGLEOPTION							2
#define DISPID_OPTBTN_BACKCOLOR											3
#define DISPID_OPTBTN_BORDERSTYLE										4
#define DISPID_OPTBTN_CONTENTTYPE										5
#define DISPID_OPTBTN_DISABLEDEVENTS								6
#define DISPID_OPTBTN_DONTREDRAW										7
#define DISPID_OPTBTN_ENABLED												DISPID_ENABLED
#define DISPID_OPTBTN_FONT													8
#define DISPID_OPTBTN_FORECOLOR											9
#define DISPID_OPTBTN_HALIGNMENT										10
#define DISPID_OPTBTN_HIMAGELIST										11
#define DISPID_OPTBTN_HOVERTIME											12
#define DISPID_OPTBTN_HWND													13
#define DISPID_OPTBTN_ICONALIGNMENT									14
#define DISPID_OPTBTN_ICONMARGINBOTTOM							15
#define DISPID_OPTBTN_ICONMARGINLEFT								16
#define DISPID_OPTBTN_ICONMARGINRIGHT								17
#define DISPID_OPTBTN_ICONMARGINTOP									18
#define DISPID_OPTBTN_IMAGE													19
#define DISPID_OPTBTN_MOUSEICON											20
#define DISPID_OPTBTN_MOUSEPOINTER									21
#define DISPID_OPTBTN_MULTILINE											22
#define DISPID_OPTBTN_OPTIONMARKONRIGHT							23
#define DISPID_OPTBTN_PROCESSCONTEXTMENUKEYS				24
#define DISPID_OPTBTN_PUSHED												25
#define DISPID_OPTBTN_PUSHLIKE											26
#define DISPID_OPTBTN_REGISTERFOROLEDRAGDROP				27
#define DISPID_OPTBTN_RIGHTTOLEFT										28
#define DISPID_OPTBTN_SELECTED											DISPID_VALUE
#define DISPID_OPTBTN_STYLE													29
#define DISPID_OPTBTN_SUPPORTOLEDRAGIMAGES					30
#define DISPID_OPTBTN_TEXT													31
#define DISPID_OPTBTN_TEXTMARGINBOTTOM							32
#define DISPID_OPTBTN_TEXTMARGINLEFT								33
#define DISPID_OPTBTN_TEXTMARGINRIGHT								34
#define DISPID_OPTBTN_TEXTMARGINTOP									35
#define DISPID_OPTBTN_USESYSTEMFONT									36
#define DISPID_OPTBTN_VALIGNMENT										37
#define DISPID_OPTBTN_VERSION												38
#define DISPID_OPTBTN_ICONINDEX											44
#define DISPID_OPTBTN_USEIMPROVEDIMAGELISTSUPPORT		45
// fingerprint
#define DISPID_OPTBTN_APPID													500
#define DISPID_OPTBTN_APPNAME												501
#define DISPID_OPTBTN_APPSHORTNAME									502
#define DISPID_OPTBTN_BUILD													503
#define DISPID_OPTBTN_CHARSET												504
#define DISPID_OPTBTN_ISRELEASE											505
#define DISPID_OPTBTN_PROGRAMMER										506
#define DISPID_OPTBTN_TESTER												507
// methods
#define DISPID_OPTBTN_ABOUT													DISPID_ABOUTBOX
#define DISPID_OPTBTN_CLICK													39
#define DISPID_OPTBTN_GETCONTROLSTATE								40
#define DISPID_OPTBTN_LOADSETTINGSFROMFILE					41
#define DISPID_OPTBTN_REFRESH												DISPID_REFRESH
#define DISPID_OPTBTN_SAVESETTINGSTOFILE						42
#define DISPID_OPTBTN_GETIDEALSIZE									43
#define DISPID_OPTBTN_FINISHOLEDRAGDROP							46


// _IOptionButtonEvents
// methods
#define DISPID_OPTBTNE_CLICK												1
#define DISPID_OPTBTNE_CONTEXTMENU									2
#define DISPID_OPTBTNE_CUSTOMDRAW										3
#define DISPID_OPTBTNE_DBLCLICK											4
#define DISPID_OPTBTNE_DESTROYEDCONTROLWINDOW				5
#define DISPID_OPTBTNE_KEYDOWN											6
#define DISPID_OPTBTNE_KEYPRESS											7
#define DISPID_OPTBTNE_KEYUP												8
#define DISPID_OPTBTNE_MCLICK												9
#define DISPID_OPTBTNE_MDBLCLICK										10
#define DISPID_OPTBTNE_MOUSEDOWN										11
#define DISPID_OPTBTNE_MOUSEENTER										12
#define DISPID_OPTBTNE_MOUSEHOVER										13
#define DISPID_OPTBTNE_MOUSELEAVE										14
#define DISPID_OPTBTNE_MOUSEMOVE										15
#define DISPID_OPTBTNE_MOUSEUP											16
#define DISPID_OPTBTNE_OLEDRAGDROP									17
#define DISPID_OPTBTNE_OLEDRAGENTER									18
#define DISPID_OPTBTNE_OLEDRAGLEAVE									19
#define DISPID_OPTBTNE_OLEDRAGMOUSEMOVE							20
#define DISPID_OPTBTNE_OWNERDRAW										21
#define DISPID_OPTBTNE_RCLICK												22
#define DISPID_OPTBTNE_RDBLCLICK										23
#define DISPID_OPTBTNE_RECREATEDCONTROLWINDOW				24
#define DISPID_OPTBTNE_RESIZEDCONTROLWINDOW					25
#define DISPID_OPTBTNE_SELECTIONCHANGED							DISPID_VALUE
#define DISPID_OPTBTNE_XCLICK												26
#define DISPID_OPTBTNE_XDBLCLICK										27


// IOLEDataObject
// properties
// methods
#define DISPID_ODO_CLEAR														1
#define DISPID_ODO_GETCANONICALFORMAT								2
#define DISPID_ODO_GETDATA													3
#define DISPID_ODO_GETFORMAT												4
#define DISPID_ODO_SETDATA													5
#define DISPID_ODO_GETDROPDESCRIPTION								6
#define DISPID_ODO_SETDROPDESCRIPTION								7
